// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBezeGk8d3FEB4QZh9C-Tq0BzisgXaJ4',
    appId: '1:999514162123:web:92509ec5eda74bb55a6c4e',
    messagingSenderId: '999514162123',
    projectId: 'hassan-fulaih-course',
    authDomain: 'hassan-fulaih-course.firebaseapp.com',
    databaseURL: 'https://hassan-fulaih-course-default-rtdb.firebaseio.com',
    storageBucket: 'hassan-fulaih-course.appspot.com',
    measurementId: 'G-YGWBSFP5GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrZS-fA-kc9ttA6VGBqD3RX5x_wJ4ab4',
    appId: '1:999514162123:android:9739e81fdf852ea95a6c4e',
    messagingSenderId: '999514162123',
    projectId: 'hassan-fulaih-course',
    databaseURL: 'https://hassan-fulaih-course-default-rtdb.firebaseio.com',
    storageBucket: 'hassan-fulaih-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOtGbkGDnJ1suJMRqz-Lp71c6BZ2oXLck',
    appId: '1:999514162123:ios:9d9ee64e591ac3755a6c4e',
    messagingSenderId: '999514162123',
    projectId: 'hassan-fulaih-course',
    databaseURL: 'https://hassan-fulaih-course-default-rtdb.firebaseio.com',
    storageBucket: 'hassan-fulaih-course.appspot.com',
    iosClientId: '999514162123-t1chn7plmo7hfl0vbmt3ua487l885a7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOtGbkGDnJ1suJMRqz-Lp71c6BZ2oXLck',
    appId: '1:999514162123:ios:9f840260efd53d295a6c4e',
    messagingSenderId: '999514162123',
    projectId: 'hassan-fulaih-course',
    databaseURL: 'https://hassan-fulaih-course-default-rtdb.firebaseio.com',
    storageBucket: 'hassan-fulaih-course.appspot.com',
    iosClientId: '999514162123-eoj6nvjcickijq7jhoqb6i1ma4n0fkge.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
